### ISSUE TITLE
fix the quadgate issue

### ISSUE THREAD

**Issue by mikejiang** [RGLab/cytolib#16]
Currently quadGate is represented as 4 independent rectGate in cytolib, which has issue with the cell events that happen to be on the intersection lines of quadrants. See https://github.com/RGLab/openCyto/issues/199#issuecomment-538585027 for details

In order to assign these cells exclusively to one of the quadrant, we will need to add a new class `quadGate` in order to achieve the non-overlapping quadrants.

**Comment by DillonHammill** [comment]
Hi @mikejiang,

Just confirming that the gates are still returned as rectangleGates for each population when extracting them from a GatingSet?

```{r}
# Populations A, B, C & D in quadGate applied to GatingSet
gs_pop_get_gate(gs, "A")
# returns rectangleGate for population A and not the quadGate object
```

So to modify the gates we should replace each of the rectangleGates for each population?

```{r}
# Update quadGate - repeat for pops A-D (rectA is rectangleGate around A)
gs_pop_set_gate(gs, "A", rectA)
```

Or would it be possible to do this?

```{r}
# quad is a new quadGate
gs_pop_set_gate(gs, c("A","B","C","D"), quad)
```

Is there a way to get the quadGate back from the GatingSet? It is difficult to know if the rectangleGate came from a quadGate or not...

```{r}
gs_pop_get_gate(gs, "A")
# return the quadGate instead of rectangleGate
```

Thanks for your help!

Dillon

**Comment by mikejiang** [comment]
If you specify population `A`, then only `A` quadrant (i,e, rectangle) should be returned. Because pop `A` is not `A,B,C,D`. I think flowJo also interprets this way.

`gs_pop_set_gate(gs, c("A","B","C","D"), quad)` does make sense though, I will see if I can make that happen quickly.

**Comment by DillonHammill** [comment]
Thanks @mikejiang!

How do you make sure this rectangle is treated as being a part of a quadGate?

For example, if you are given a cytoframe or cytoset to subset with rectA. This rectangle is treated just like any other (rectangle) right? So `Subset(cf, rectA)` does not return the same indices as `gs_pop_get_data(gs, "A")`?

**Comment by mikejiang** [comment]
I will attach the original quadgate info as the attribue to `rectangleGate` object returned by `gh_pop_get_gate` so that we know it is part of a quadGate.
Regarding to update quadgate, I am leaning toward `gs_pop_set_gate(gs, "A", new.quadgate)`, which will verify if `A` was indeed a quadrant before updating it. The assumption is users intend for this change to be automatically propagated to `B,C,D` . 
Sounds reasonable behavior? @jacobpwagner @gfinak

**Comment by DillonHammill** [comment]
That would be great!

**Comment by mikejiang** [comment]
Ok. Here is what we've got so far (check out the latest flowWorkspace)
```r
qg2 <- quadGate(list(`FSC-H` = 500, `SSC-H` = 600))
  gs_pop_add(gs, qg2, names = c("A", "B", "C", "D"))
  recompute(gs)
```
![image](https://user-images.githubusercontent.com/1385649/72940340-915a8600-3d23-11ea-83eb-6ebeb61e3e74.png)

Retrieve quadgate info
```r
  g1 <- gs_pop_get_gate(gs, "A")[[1]]
> g1
Rectangular gate 'A' with dimensions:
  FSC-H: (-Inf,500)
  SSC-H: (600,Inf)
> attributes(g1)[c("quadrants", "quadintersection")]
$quadrants
A B C D 
1 2 3 4 

$quadintersection
FSC-H SSC-H 
  500   600 
```
Update quadgate
```r
>   qg2@boundary[[1]] <- 200
>   gh_pop_set_gate(gs[[1]], c("A"), qg2)
>   g1 <- gs_pop_get_gate(gs, "A")[[1]]
> g1
Rectangular gate 'A' with dimensions:
  FSC-H: (-Inf,200)
  SSC-H: (600,Inf)
```
All the rest quadrants also get updated
```r
>   g1 <- gs_pop_get_gate(gs, "B")[[1]]
> g1
Rectangular gate 'B' with dimensions:
  FSC-H: (200,Inf)
  SSC-H: (600,Inf)
```
```r
autoplot(gs[[1]], c("A", "B", "C", "D"))
```
![image](https://user-images.githubusercontent.com/1385649/72941189-3a55b080-3d25-11ea-9c26-01009f927df2.png)

**Comment by DillonHammill** [comment]
That's fantastic thanks @mikejiang! I will play around with it today.

Out of curiosity, is it still possible to also update each of the rectangleGates individually if we need to (i.e. `gs_pop_set_gate(gs, "A", rectA)` as so on)?

**Comment by mikejiang** [comment]
Yes.

**Comment by DillonHammill** [comment]
Great thank you! I will let you know if I run into any problems.

**Comment by DillonHammill** [comment]
Thanks again @mikejiang, this saved me a lot of work! Really appreciate it! Works like a charm :)
