### ISSUE TITLE
write portable configure scripts for windows

### ISSUE THREAD

**Issue by mikejiang** [RGLab/cytolib#18]
We are currently using the `configure` script auto-generated through `autoconf` for writing package version info into the c++ header file. However this script doesn't seem to be portable for windows

```bash
cytolib>R CMD INSTALL .
* installing to library 'C:/Users/wjiang2/Documents/R/win-library/3.6'
* installing *source* package 'cytolib' ...
** using staged installation
chmod: not found
configure.win: error: cannot create configure.win.lineno; rerun with a POSIX shell
ERROR: configuration failed for package 'cytolib'
```

Unless we can find the tool that can generate `mingw` version of `configure.win` file , we may consider to use R to perform such pre-installation configuring process 
https://github.com/kevinushey/configure

**Comment by mikejiang** [comment]
@kevinushey 's `configure` R package works beautifully !

**Comment by kevinushey** [comment]
Very happy to hear it :-)
