### ISSUE TITLE
cytolib installation error with Rtools 4.0 + R-testing

### ISSUE THREAD

**Issue by hpages** [RGLab/cytolib#31]
Hi Mike,

In addition to the usual devel builds, we've started to build a small subset of Bioconductor packages using Rtools40 and R-testing:

  https://bioconductor.org/checkResults/3.11/bioc-testing-LATEST/

We're hoping that having these experimental builds will help us get ready for when R core decides to officially make the switch to Rtools40.

This is a heads-up that cytolib fails to install with Rtools40 + R-testing.

Best,
H.

**Comment by mikejiang** [comment]
It is probably because the current `protobuf` library binary on bioc server was built by MSYS1.0 + Rtools3.x
We will try to test it with Rtools40 and update the building instructions in `INSTALL` accordingly

**Comment by hpages** [comment]
Sounds good. Thanks Mike
