### ISSUE TITLE
Revert to Artistic lisence - The Fred Hutchinson software license makes CRAN packages impossible

### ISSUE THREAD

**Issue by ustervbo** [RGLab/cytolib#35]
I maintain the R package [`beadplexr`](https://CRAN.R-project.org/package=beadplexr), which evaluates bead assays (like LegendPLex or CBA) acquired on a flow cytometer. For reading the fcs files, I rely on `flowCore` which imports `cytolib` in the coming version.

The restrictions in the Fred Hutchinson software license used by `cytolib`:

> Derviative works must be free, open source, and non-commercial, academic, research only. Commercial and internal business use is not permitted.

makes packages such as mine unacceptable to CRAN.

Would it be possible to revert to the previous Artistic license?

**Comment by gfinak** [comment]
Nope.
I suggest talking to CRAN to get an exception, or importing the older flowCore code into your package.
