### ISSUE TITLE
add libver log file to archive folder

### ISSUE THREAD

**Issue by mikejiang** [RGLab/cytolib#7]
When `GatingSet` is archived, we will also try to save the versions of protobuf,h5 used by cytolib. The txt file won't be used by program but can provide some troubleshooting information to users when something goes wrong with loading/reading archive.

**Comment by mikejiang** [comment]
@gfinak , I ended up recording the lib info in the protobuf file at `c++` level.
`R` can use `verbose`  flag to optionally print the versions of the libraries that were used to archive the `GatingSet`
```r
 gs <- load_gs(tmp, verbose = TRUE)
The GatingSet was archived by:
cytolib: 1.9.8
protobuf: 3010000
HDF5: 1.10.5
```

**Comment by gfinak** [comment]
This is really useful, thanks.
