### ISSUE TITLE
cytolib installation failed under OSX 10.14

### ISSUE THREAD

**Issue by akhst7** [RGLab/cytolib#8]
Installation of cytolib failed under OSX 10.14 with a following command;
`R CMD INSTALL cytolib-trunk.zip`

Output is as follows;

> Bioconductor version 3.7 (BiocInstaller 1.30.0), ?biocLite for help
Successfully loaded .Rprofile at Wed Oct 10 20:01:39 2018
Error in rawToChar(block[seq_len(ns)]) : embedded nul in string: 'PK\003\004\n\0\0\0\0\0\xd8k\034M\0\0\0\0\0\0\0\0\0\0\0\0\016\0\t\0cytolib-trunk/UT\005\0\001\xf8\xb0\x85[PK\003\004\n\0\0\0\b\0\xd8k\034M\002\xee(5\x9a\001\0\0w\002\0\0\031\0\t\0cytolib-trunk/DES`

**Comment by gfinak** [comment]
Can you provide details on how you obtain the file `cytolib-trunk.zip` in the first place?
Note that this package is passing tests on Bioconductor and local machines here at the Hutch, so I'm skeptical that this isn't caused by something local to your system.

**Comment by mikejiang** [comment]
obsolete bioc version
